all: CardGame

CardGame: Deck.o Player.o Card.o Rank.o Suit.o GameEngine.o main.o
	g++ -o CardGame.exe Deck.o Player.o Card.o Rank.o Suit.o GameEngine.o main.o

Deck.o:
	g++ Deck.cpp -o Deck.o -c

Player.o:
	g++ Player.cpp -o Player.o -c

Card.o:
	g++ Card.cpp -o Card.o -c

Rank.o:
	g++ Rank.cpp -o Rank.o -c

Suit.o:
	g++ Suit.cpp -o Suit.o -c

GameEngine.o:
	g++ GameEngine.cpp -o GameEngine.o -c

main.o:
	g++ main.cpp -o main.o -c

clean:
	rm -f *.o *.exe
