all: CardGameDurak

CardGameDurak: Main.o Card.o Deck.o Player.o GameEngine.o Rank.o Suit.o
	g++ -o CardGameDurak.exe Main.o Card.o Deck.o Player.o GameEngine.o Rank.o Suit.o

Main.o:
	g++ Main.cpp -o Main.o -c

Card.o:
	g++ Card.cpp -o Card.o -c

Deck.o:
	g++ Deck.cpp -o Deck.o -c

Player.o:
	g++ Player.cpp -o Player.o -c

GameEngine.o:
	g++ GameEngine.cpp -o GameEngine.o -c

Rank.o:
	g++ Rank.cpp -o Rank.o -c

Suit.o:
	g++ Suit.cpp -o Suit.o -c

clean:
	rm -f *.o *.exe
